USE [Qly_Nvien]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[KYCONG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MAKYCONG] [int] NOT NULL,
	[THANG] [int] NULL,
	[NAM] [int] NULL,
	[KHOA] [bit] NULL,
	[NGAYTINHCONG] [datetime] NULL,
	[NGAYCONGTRONGTHANG] [float] NULL,
	[MACTY] [nvarchar](4) NULL,
	[TRANGTHAI] [bit] NULL,
CONSTRAINT [PK_KYCONG] PRIMARY KEY CLUSTERED
(
	[ID] ASC
) WITH (PAD_INDEX=OFF, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS=ON, OPTIMIZE_FOR_SEQUENTIAL_KEY=OFF) ON [PRIMARY]
)ON [PRIMARY]
GO