CREATE TABLE [dbo].[BANGCONG](
	[MABC] [int] IDENTITY(1,1) NOT NULL,
	[MANV] [int] NULL,
	[ID_LC] [int] NULL,
	[ID_CC] [int] NULL,
 CONSTRAINT [PK_BANGCONG] PRIMARY KEY CLUSTERED 
(
	[MABC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BANGCONG]  WITH CHECK ADD  CONSTRAINT [FK_BANGCONG_CHAMCONG] FOREIGN KEY([ID_CC])
REFERENCES [dbo].[CHAMCONG] ([ID_CC])
GO

ALTER TABLE [dbo].[BANGCONG] CHECK CONSTRAINT [FK_BANGCONG_CHAMCONG]
GO
ALTER TABLE [dbo].[BANGCONG]  WITH CHECK ADD  CONSTRAINT [FK_BANGCONG_LOAICONG] FOREIGN KEY([ID_LC])
REFERENCES [dbo].[LOAICONG] ([ID_LC])
GO

ALTER TABLE [dbo].[BANGCONG] CHECK CONSTRAINT [FK_BANGCONG_LOAICONG]