CREATE TABLE [dbo].[CHAMCONG](
	[ID_CC] [int] IDENTITY(1,1) NOT NULL,
	[NGAY] [int] NULL,
	[THANG] [int] NULL,
	[NAM] [int] NULL,
	[GIOVAO] [int] NULL,
	[PHUTVAO] [int] NULL,
	[GIORA] [int] NULL,
	[PHUTRA] [int] NULL,
	[BUOINGHIPHEP] [int] NULL,
 CONSTRAINT [PK_CHAMCONG] PRIMARY KEY CLUSTERED 
(
	[ID_CC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]