CREATE TABLE [dbo].[CONGTY](
	[ID_CTY] [int] IDENTITY(1,1) NOT NULL,
	[TENCTY] [nvarchar](max) NULL,
	[SĐT] [nvarchar](max) NULL,
	[EMAIL] [nvarchar](max) NULL,
	[DIACHI] [nvarchar](max) NULL,
 CONSTRAINT [PK_CONGTY] PRIMARY KEY CLUSTERED 
(
	[ID_CTY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]