CREATE TABLE [dbo].[HOPDONG](
	[SOHD] [nvarchar](50) NOT NULL,
	[NGAYBDAU] [datetime] NULL,
	[NGAYKTHUC] [datetime] NULL,
	[NGAYKY] [datetime] NULL,
	[NOIDUNG] [nvarchar](max) NULL,
	[LANKY] [int] NULL,
	[THOIHAN] [nvarchar](max) NULL,
	[HESOLUONG] [float] NULL,
	[MANV] [int] NULL,
	[ID_CTY] [int] NULL,
	[DELETED_BY] [int] NULL,
	[DELETED_DATE] [datetime] NULL,
	[UPDATED_BY] [int] NULL,
	[UPDATED_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATE] [datetime] NULL,
 CONSTRAINT [PK_HOPDONG_1] PRIMARY KEY CLUSTERED 
(
	[SOHD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[HOPDONG]  WITH CHECK ADD  CONSTRAINT [FK_HOPDONG_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO

ALTER TABLE [dbo].[HOPDONG] CHECK CONSTRAINT [FK_HOPDONG_NHANVIEN]