CREATE TABLE [dbo].[KHENTHUONGKYLUAT](
	[SOQUYETDINH] [nvarchar](50) NOT NULL,
	[LYDO] [nvarchar](max) NULL,
	[NOIDUNG] [nvarchar](max) NULL,
	[NGAY] [datetime] NULL,
	[MANV] [int] NULL,
	[LOAI] [int] NULL,
	[TUNGAY] [datetime] NULL,
	[DENNGAY] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATE] [datetime] NULL,
	[DELETED_BY] [int] NULL,
	[DELETED_DATE] [datetime] NULL,
	[UPDATED_BY] [int] NULL,
	[UPDATED_DATE] [datetime] NULL,
 CONSTRAINT [PK_KHENTHUONGKYLUAT_1] PRIMARY KEY CLUSTERED 
(
	[SOQUYETDINH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[KHENTHUONGKYLUAT]  WITH CHECK ADD  CONSTRAINT [FK_KHENTHUONGKYLUAT_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO

ALTER TABLE [dbo].[KHENTHUONGKYLUAT] CHECK CONSTRAINT [FK_KHENTHUONGKYLUAT_NHANVIEN]