CREATE TABLE [dbo].[LOAICA](
	[ID_LCA] [int] IDENTITY(1,1) NOT NULL,
	[TENLCA] [nvarchar](max) NULL,
	[HESO] [float] NULL,
 CONSTRAINT [PK_LOAICA] PRIMARY KEY CLUSTERED 
(
	[ID_LCA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]