CREATE TABLE [dbo].[LOAICONG](
	[ID_LC] [int] IDENTITY(1,1) NOT NULL,
	[TENLC] [nvarchar](50) NULL,
	[HESO] [float] NULL,
 CONSTRAINT [PK_LOAICONG] PRIMARY KEY CLUSTERED 
(
	[ID_LC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]