CREATE TABLE [dbo].[NHANVIEN](
	[MANV] [int] IDENTITY(1,1) NOT NULL,
	[HOTEN] [nvarchar](max) NULL,
	[GIOITINH] [bit] NULL,
	[NGAYSINH] [datetime] NULL,
	[SDT] [nvarchar](max) NULL,
	[DIACHI] [nvarchar](max) NULL,
	[EMAIL] [nvarchar](max) NULL,
	[ID_PB] [int] NULL,
	[ID_BP] [int] NULL,
	[ID_CV] [int] NULL,
	[ID_TD] [int] NULL,
	[ID_CTY] [int] NULL,
	[HINHANH] [varbinary](max) NULL,
	[DATHOIVIEC] [bit] NULL,
 CONSTRAINT [PK_NHANVIEN] PRIMARY KEY CLUSTERED 
(
	[MANV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]