CREATE TABLE [dbo].[NHANVIEN_THOIVIEC](
	[SOQD] [nvarchar](50) NOT NULL,
	[NGAYNOPDON] [datetime] NULL,
	[NGAYNGHI] [datetime] NULL,
	[LYDO] [nvarchar](max) NULL,
	[GHICHU] [nvarchar](max) NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATE_BY] [int] NULL,
	[UPDATE_DATE] [datetime] NULL,
	[DELETED_BY] [int] NULL,
	[DELETED_DATE] [datetime] NULL,
 CONSTRAINT [PK_NHANVIEN_THOIVIEC] PRIMARY KEY CLUSTERED 
(
	[SOQD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]