CREATE TABLE [dbo].[TANGCA](
	[ID_TC] [int] IDENTITY(1,1) NOT NULL,
	[NAM] [int] NULL,
	[THANG] [int] NULL,
	[NGAY] [int] NULL,
	[SOGIO] [float] NULL,
	[MANV] [int] NULL,
	[ID_LCA] [int] NULL,
 CONSTRAINT [PK_TANGCA] PRIMARY KEY CLUSTERED 
(
	[ID_TC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TANGCA]  WITH CHECK ADD  CONSTRAINT [FK_TANGCA_LOAICA] FOREIGN KEY([ID_LCA])
REFERENCES [dbo].[LOAICA] ([ID_LCA])
GO

ALTER TABLE [dbo].[TANGCA] CHECK CONSTRAINT [FK_TANGCA_LOAICA]