//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMCONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHAMCONG()
        {
            this.BANGCONG = new HashSet<BANGCONG>();
            this.BANGCONG1 = new HashSet<BANGCONG>();
        }
    
        public int ID_CC { get; set; }
        public Nullable<int> NGAY { get; set; }
        public Nullable<int> THANG { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<int> GIOVAO { get; set; }
        public Nullable<int> PHUTVAO { get; set; }
        public Nullable<int> GIORA { get; set; }
        public Nullable<int> PHUTRA { get; set; }
        public Nullable<int> BUOINGHIPHEP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGCONG> BANGCONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGCONG> BANGCONG1 { get; set; }
    }
}
