//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Qly_NvienEntities2 : DbContext
    {
        public Qly_NvienEntities2()
            : base("name=Qly_NvienEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANGCONG> BANGCONG { get; set; }
        public virtual DbSet<BANGCONG_NHANVIEN_CHITIET> BANGCONG_NHANVIEN_CHITIET { get; set; }
        public virtual DbSet<BANGLUONG> BANGLUONG { get; set; }
        public virtual DbSet<BAOCAO> BAOCAO { get; set; }
        public virtual DbSet<BOPHAN> BOPHAN { get; set; }
        public virtual DbSet<CONGTY> CONGTY { get; set; }
        public virtual DbSet<CHAMCONG> CHAMCONG { get; set; }
        public virtual DbSet<CHUCVU> CHUCVU { get; set; }
        public virtual DbSet<HOPDONG> HOPDONG { get; set; }
        public virtual DbSet<KYCONG> KYCONG { get; set; }
        public virtual DbSet<KYCONGCHITIET> KYCONGCHITIET { get; set; }
        public virtual DbSet<KHENTHUONGKYLUAT> KHENTHUONGKYLUAT { get; set; }
        public virtual DbSet<LOAICA> LOAICA { get; set; }
        public virtual DbSet<LOAICONG> LOAICONG { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<NHANVIEN_BAOCAO> NHANVIEN_BAOCAO { get; set; }
        public virtual DbSet<NHANVIEN_NANGLUONG> NHANVIEN_NANGLUONG { get; set; }
        public virtual DbSet<NHANVIEN_THOIVIEC> NHANVIEN_THOIVIEC { get; set; }
        public virtual DbSet<PHONGBAN> PHONGBAN { get; set; }
        public virtual DbSet<TANGCA> TANGCA { get; set; }
        public virtual DbSet<TRINHDO> TRINHDO { get; set; }
    }
}
