//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Qly_NvienEntities1 : DbContext
    {
        public Qly_NvienEntities1()
            : base("name=Qly_NvienEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANGCONG> BANGCONG { get; set; }
        public virtual DbSet<BOPHAN> BOPHAN { get; set; }
        public virtual DbSet<CHAMCONG> CHAMCONG { get; set; }
        public virtual DbSet<CHUCVU> CHUCVU { get; set; }
        public virtual DbSet<KHENTHUONGKYLUAT> KHENTHUONGKYLUAT { get; set; }
        public virtual DbSet<LOAICA> LOAICA { get; set; }
        public virtual DbSet<LOAICONG> LOAICONG { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<PHONGBAN> PHONGBAN { get; set; }
        public virtual DbSet<TANGCA> TANGCA { get; set; }
        public virtual DbSet<TRINHDO> TRINHDO { get; set; }
    }
}
